repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--config=./pyproject.toml]
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
