language: python
python:
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
  - pip install coveralls
script:
  - poetry run pytest --cov=dsplot
after_success:
  - coveralls
